### ISSUE TITLE
 Similar project: gfork

### ISSUE THREAD

**Issue by laggingreflex** [TerriaJS/npmgitdev#9]
I've created a similar project: [gfork](https://github.com/laggingreflex/gfork). It offers all functionalities of this project, and more. Check it out! :)

**Comment by kring** [comment]
Hi @laggingreflex, it looks like an interesting project, but as far as I can tell it doesn't do the main thing that npmgitdev is meant to do, and doesn't solve the same problem.

With npmgitdev, we aim to use a repo cloned from git as a dependency _exactly as if it were a normal npm dependency_.  That does _not_ mean that dependencies of the cloned repo are installed into the repo's `node_modules` directory.  Instead, npm's de-duplication algorithm is able to ensure that only one copy of any shared, compatible dependencies is installed, and that one copy is installed in the root where you ran `npm install`, not inside individual module directories.  This is really really important because there are npm modules out there that do horrible, broken things when multiple copies are loaded, usually without any indication that this is the cause.  webpack and its loaders are notorious for this.

I tried to explain the problem npmgitdev is meant to solve in this npm issue:
https://github.com/npm/npm/issues/12506

But the truth is, it's pretty hard to explain unless you've run into it.  In any case, any solution that involves `npm link` won't work, because `npm link` is conceptually broken for the use-cases where npmgitdev is meant to apply.
